import React from "react";
import { FormattedMessage } from "react-intl";
import messages from "containers/Commons/HotelSearchFormCommon/messages";

export const EZ_AMENITY = [
  {
    id: 178,
    val: 178,
    title: "Đi được bằng thang máy",
    label: <FormattedMessage {...messages.ezAme178} />,
  },
  {
    id: 179,
    val: 179,
    title: "Phòng tắm cho người già",
    label: <FormattedMessage {...messages.ezAme179} />,
  },
  {
    id: 180,
    val: 180,
    title: "Phòng tắm cho người khuyết tật",
    label: <FormattedMessage {...messages.ezAme180} />,
  },
  {
    id: 181,
    val: 181,
    title: "Phòng ngủ cho người khuyết tật",
    label: <FormattedMessage {...messages.ezAme181} />,
  },
  {
    id: 182,
    val: 182,
    title: "Dây khẩn cấp trong phòng tắm",
    label: <FormattedMessage {...messages.ezAme182} />,
  },
  {
    id: 183,
    val: 183,
    title: "Bồn thấp",
    label: <FormattedMessage {...messages.ezAme183} />,
  },
  {
    id: 184,
    val: 184,
    title: "Bồn vệ sinh có tay vịn",
    label: <FormattedMessage {...messages.ezAme184} />,
  },
  {
    id: 185,
    val: 185,
    title: "Phòng tắm sen dành cho người đi xe lăn",
    label: <FormattedMessage {...messages.ezAme185} />,
  },
  {
    id: 186,
    val: 186,
    title: "Phòng hoàn toàn có thể sử dụng xe lăn",
    label: <FormattedMessage {...messages.ezAme186} />,
  },
  {
    id: 187,
    val: 187,
    title: "Phòng tầng trệt",
    label: <FormattedMessage {...messages.ezAme187} />,
  },
  {
    id: 188,
    val: 188,
    title: "Ghế tắm",
    label: <FormattedMessage {...messages.ezAme188} />,
  },
  {
    id: 189,
    val: 189,
    title: "Nhà vệ sinh có tay vịn",
    label: <FormattedMessage {...messages.ezAme189} />,
  },
  {
    id: 190,
    val: 190,
    title: "Tầng trên đi được bằng thang máy",
    label: <FormattedMessage {...messages.ezAme190} />,
  },
  {
    id: 191,
    val: 191,
    title: "Tầng trên đi được bằng cầu thang",
    label: <FormattedMessage {...messages.ezAme191} />,
  },
  {
    id: 192,
    val: 192,
    title: "Phòng tắm sen thường",
    label: <FormattedMessage {...messages.ezAme192} />,
  },
  {
    id: 193,
    val: 193,
    title: "Phòng tắm phụ",
    label: <FormattedMessage {...messages.ezAme193} />,
  },
  {
    id: 194,
    val: 194,
    title: "Áo choàng tắm",
    label: <FormattedMessage {...messages.ezAme194} />,
  },
  {
    id: 195,
    val: 195,
    title: "Bồn tắm",
    label: <FormattedMessage {...messages.ezAme195} />,
  },
  {
    id: 196,
    val: 196,
    title: "Bồn tắm hoặc vòi sen",
    label: <FormattedMessage {...messages.ezAme196} />,
  },
  {
    id: 197,
    val: 197,
    title: "Chậu vệ sinh",
    label: <FormattedMessage {...messages.ezAme197} />,
  },
  {
    id: 198,
    val: 198,
    title: "Xà phòng tắm",
    label: <FormattedMessage {...messages.ezAme198} />,
  },
  {
    id: 199,
    val: 199,
    title: "Dầu dưỡng tóc",
    label: <FormattedMessage {...messages.ezAme199} />,
  },
  {
    id: 200,
    val: 200,
    title: "Đồ dùng nhà tắm miễn phí",
    label: <FormattedMessage {...messages.ezAme200} />,
  },
  {
    id: 201,
    val: 201,
    title: "Phòng tắm cho khách",
    label: <FormattedMessage {...messages.ezAme201} />,
  },
  {
    id: 202,
    val: 202,
    title: "Máy sấy tóc",
    label: <FormattedMessage {...messages.ezAme202} />,
  },
  {
    id: 203,
    val: 203,
    title: "Phòng tắm riêng",
    label: <FormattedMessage {...messages.ezAme203} />,
  },
  {
    id: 204,
    val: 204,
    title: "Phòng xông hơi",
    label: <FormattedMessage {...messages.ezAme204} />,
  },
  {
    id: 205,
    val: 205,
    title: "Dầu gội",
    label: <FormattedMessage {...messages.ezAme205} />,
  },
  {
    id: 206,
    val: 206,
    title: "Phòng tắm dùng chung",
    label: <FormattedMessage {...messages.ezAme206} />,
  },
  {
    id: 207,
    val: 207,
    title: "Toilet chung",
    label: <FormattedMessage {...messages.ezAme207} />,
  },
  {
    id: 208,
    val: 208,
    title: "Vòi sen",
    label: <FormattedMessage {...messages.ezAme208} />,
  },
  {
    id: 209,
    val: 209,
    title: "Mũ tắm",
    label: <FormattedMessage {...messages.ezAme209} />,
  },
  {
    id: 210,
    val: 210,
    title: "Dép",
    label: <FormattedMessage {...messages.ezAme210} />,
  },
  {
    id: 211,
    val: 211,
    title: "Bồn tắm thủy lực",
    label: <FormattedMessage {...messages.ezAme211} />,
  },
  {
    id: 212,
    val: 212,
    title: "Nhà vệ sinh",
    label: <FormattedMessage {...messages.ezAme212} />,
  },
  {
    id: 213,
    val: 213,
    title: "Giấy vệ sinh",
    label: <FormattedMessage {...messages.ezAme213} />,
  },
  {
    id: 214,
    val: 214,
    title: "Bàn chải đánh răng",
    label: <FormattedMessage {...messages.ezAme214} />,
  },
  {
    id: 215,
    val: 215,
    title: "Cổng an toàn cho bé",
    label: <FormattedMessage {...messages.ezAme215} />,
  },
  {
    id: 216,
    val: 216,
    title: "Ban trò chơi / câu đố",
    label: <FormattedMessage {...messages.ezAme216} />,
  },
  {
    id: 217,
    val: 217,
    title: "Sách, DVD hoặc nhạc cho trẻ em",
    label: <FormattedMessage {...messages.ezAme217} />,
  },
  {
    id: 218,
    val: 218,
    title: "Nắp ổ cắm an toàn",
    label: <FormattedMessage {...messages.ezAme218} />,
  },
  {
    id: 219,
    val: 219,
    title: "Tiệc nướng ngoài trời",
    label: <FormattedMessage {...messages.ezAme219} />,
  },
  {
    id: 220,
    val: 220,
    title: "Chai nước",
    label: <FormattedMessage {...messages.ezAme220} />,
  },
  {
    id: 221,
    val: 221,
    title: "Chocolate/Cookies",
    label: <FormattedMessage {...messages.ezAme221} />,
  },
  {
    id: 222,
    val: 222,
    title: "máy pha cà phê",
    label: <FormattedMessage {...messages.ezAme222} />,
  },
  {
    id: 223,
    val: 223,
    title: "Khu vực ăn uống",
    label: <FormattedMessage {...messages.ezAme223} />,
  },
  {
    id: 224,
    val: 224,
    title: "Bàn ăn",
    label: <FormattedMessage {...messages.ezAme224} />,
  },
  {
    id: 225,
    val: 225,
    title: "Máy rửa chén",
    label: <FormattedMessage {...messages.ezAme225} />,
  },
  {
    id: 226,
    val: 226,
    title: "Ấm đun nước điện",
    label: <FormattedMessage {...messages.ezAme226} />,
  },
  {
    id: 227,
    val: 227,
    title: "Trái cây",
    label: <FormattedMessage {...messages.ezAme227} />,
  },
  {
    id: 228,
    val: 228,
    title: "Ghế cao",
    label: <FormattedMessage {...messages.ezAme228} />,
  },
  {
    id: 229,
    val: 229,
    title: "Phòng bếp",
    label: <FormattedMessage {...messages.ezAme229} />,
  },
  {
    id: 230,
    val: 230,
    title: "Bếp nhỏ",
    label: <FormattedMessage {...messages.ezAme230} />,
  },
  {
    id: 231,
    val: 231,
    title: "Đồ dùng nhà bếp",
    label: <FormattedMessage {...messages.ezAme231} />,
  },
  {
    id: 232,
    val: 232,
    title: "Lò vi sóng",
    label: <FormattedMessage {...messages.ezAme232} />,
  },
  {
    id: 233,
    val: 233,
    title: "Minibar",
    label: <FormattedMessage {...messages.ezAme233} />,
  },
  {
    id: 234,
    val: 234,
    title: "Khu ăn uống ngoài trời",
    label: <FormattedMessage {...messages.ezAme234} />,
  },
  {
    id: 235,
    val: 235,
    title: "Bàn ghế ngoài trời",
    label: <FormattedMessage {...messages.ezAme235} />,
  },
  {
    id: 236,
    val: 236,
    title: "Lò nướng",
    label: <FormattedMessage {...messages.ezAme236} />,
  },
  {
    id: 237,
    val: 237,
    title: "Tủ lạnh",
    label: <FormattedMessage {...messages.ezAme237} />,
  },
  {
    id: 238,
    val: 238,
    title: "Bếp đun",
    label: <FormattedMessage {...messages.ezAme238} />,
  },
  {
    id: 239,
    val: 239,
    title: "Máy pha trà / cà phê",
    label: <FormattedMessage {...messages.ezAme239} />,
  },
  {
    id: 240,
    val: 240,
    title: "Máy nướng bánh mì",
    label: <FormattedMessage {...messages.ezAme240} />,
  },
  {
    id: 241,
    val: 241,
    title: "Ly rượu",
    label: <FormattedMessage {...messages.ezAme241} />,
  },
  {
    id: 242,
    val: 242,
    title: "Rượu vang/Sâm panh",
    label: <FormattedMessage {...messages.ezAme242} />,
  },
  {
    id: 243,
    val: 243,
    title: "Đầu đọc đĩa Blu-ray",
    label: <FormattedMessage {...messages.ezAme243} />,
  },
  {
    id: 244,
    val: 244,
    title: "Truyền hình cáp",
    label: <FormattedMessage {...messages.ezAme244} />,
  },
  {
    id: 245,
    val: 245,
    title: "Đầu đĩa CD",
    label: <FormattedMessage {...messages.ezAme245} />,
  },
  {
    id: 246,
    val: 246,
    title: "Máy vi tính",
    label: <FormattedMessage {...messages.ezAme246} />,
  },
  {
    id: 247,
    val: 247,
    title: "Đầu đĩa DVD",
    label: <FormattedMessage {...messages.ezAme247} />,
  },
  {
    id: 248,
    val: 248,
    title: "Máy fax",
    label: <FormattedMessage {...messages.ezAme248} />,
  },
  {
    id: 249,
    val: 249,
    title: "Tivi màn hình phẳng",
    label: <FormattedMessage {...messages.ezAme249} />,
  },
  {
    id: 250,
    val: 250,
    title: "Máy chơi game",
    label: <FormattedMessage {...messages.ezAme250} />,
  },
  {
    id: 251,
    val: 251,
    title: "Máy chơi game - Nintendo Wii",
    label: <FormattedMessage {...messages.ezAme251} />,
  },
  {
    id: 252,
    val: 252,
    title: "Máy chơi game - PS2",
    label: <FormattedMessage {...messages.ezAme252} />,
  },
  {
    id: 253,
    val: 253,
    title: "Máy chơi game - PS3",
    label: <FormattedMessage {...messages.ezAme253} />,
  },
  {
    id: 254,
    val: 254,
    title: "Máy chơi game - PS4",
    label: <FormattedMessage {...messages.ezAme254} />,
  },
  {
    id: 255,
    val: 255,
    title: "Máy chơi game - Wii U",
    label: <FormattedMessage {...messages.ezAme255} />,
  },
  {
    id: 256,
    val: 256,
    title: "Máy chơi game - Xbox 360",
    label: <FormattedMessage {...messages.ezAme256} />,
  },
  {
    id: 257,
    val: 257,
    title: "Máy chơi game - Xbox One",
    label: <FormattedMessage {...messages.ezAme257} />,
  },
  {
    id: 258,
    val: 258,
    title: "iPad",
    label: <FormattedMessage {...messages.ezAme258} />,
  },
  {
    id: 259,
    val: 259,
    title: "Đế cắm iPod",
    label: <FormattedMessage {...messages.ezAme259} />,
  },
  {
    id: 260,
    val: 260,
    title: "Máy tính xách tay",
    label: <FormattedMessage {...messages.ezAme260} />,
  },
  {
    id: 261,
    val: 261,
    title: "Két an toàn cỡ laptop",
    label: <FormattedMessage {...messages.ezAme261} />,
  },
  {
    id: 262,
    val: 262,
    title: "Thiết bị Hotspot di động",
    label: <FormattedMessage {...messages.ezAme262} />,
  },
  {
    id: 263,
    val: 263,
    title: "Kênh truyền hình trả tiền",
    label: <FormattedMessage {...messages.ezAme263} />,
  },
  {
    id: 264,
    val: 264,
    title: "Radio",
    label: <FormattedMessage {...messages.ezAme264} />,
  },
  {
    id: 265,
    val: 265,
    title: "Truyền hình vệ tinh",
    label: <FormattedMessage {...messages.ezAme265} />,
  },
  {
    id: 266,
    val: 266,
    title: "Điện thoại thông minh",
    label: <FormattedMessage {...messages.ezAme266} />,
  },
  {
    id: 267,
    val: 267,
    title: "Dịch vụ truyền video (như Netflix)",
    label: <FormattedMessage {...messages.ezAme267} />,
  },
  {
    id: 268,
    val: 268,
    title: "Điện thoại",
    label: <FormattedMessage {...messages.ezAme268} />,
  },
  {
    id: 269,
    val: 269,
    title: "TV",
    label: <FormattedMessage {...messages.ezAme269} />,
  },
  {
    id: 270,
    val: 270,
    title: "Video",
    label: <FormattedMessage {...messages.ezAme270} />,
  },
  {
    id: 271,
    val: 271,
    title: "Trò chơi điện tử",
    label: <FormattedMessage {...messages.ezAme271} />,
  },
  {
    id: 272,
    val: 272,
    title: "Ban công",
    label: <FormattedMessage {...messages.ezAme272} />,
  },
  {
    id: 273,
    val: 273,
    title: "Nhìn ra thành phố",
    label: <FormattedMessage {...messages.ezAme273} />,
  },
  {
    id: 274,
    val: 274,
    title: "Nhìn a vườn",
    label: <FormattedMessage {...messages.ezAme274} />,
  },
  {
    id: 275,
    val: 275,
    title: "Hướng nhìn sân trong",
    label: <FormattedMessage {...messages.ezAme275} />,
  },
  {
    id: 276,
    val: 276,
    title: "Nhìn ra hồ",
    label: <FormattedMessage {...messages.ezAme276} />,
  },
  {
    id: 277,
    val: 277,
    title: "Nhìn từ trên cao",
    label: <FormattedMessage {...messages.ezAme277} />,
  },
  {
    id: 278,
    val: 278,
    title: "Nhìn ra núi",
    label: <FormattedMessage {...messages.ezAme278} />,
  },
  {
    id: 279,
    val: 279,
    title: "Nhìn ra biển",
    label: <FormattedMessage {...messages.ezAme279} />,
  },
  {
    id: 280,
    val: 280,
    title: "Sân trong nhà",
    label: <FormattedMessage {...messages.ezAme280} />,
  },
  {
    id: 281,
    val: 281,
    title: "Nhìn ra bể bơi",
    label: <FormattedMessage {...messages.ezAme281} />,
  },
  {
    id: 282,
    val: 282,
    title: "Nhìn ra phố (yên tĩnh)",
    label: <FormattedMessage {...messages.ezAme282} />,
  },
  {
    id: 283,
    val: 283,
    title: "Nhìn ra sông",
    label: <FormattedMessage {...messages.ezAme283} />,
  },
  {
    id: 284,
    val: 284,
    title: "Sân hiên",
    label: <FormattedMessage {...messages.ezAme284} />,
  },
  {
    id: 285,
    val: 285,
    title: "Cảnh quan",
    label: <FormattedMessage {...messages.ezAme285} />,
  },
  {
    id: 286,
    val: 286,
    title: "Bộ chuyển đổi",
    label: <FormattedMessage {...messages.ezAme286} />,
  },
  {
    id: 287,
    val: 287,
    title: "Điều hòa nhiệt độ",
    label: <FormattedMessage {...messages.ezAme287} />,
  },
];
